model:
  target: AutoEncoder.autoencoder.AutoEncoderKL
  embed_dim: 3
  params:
    ddconfig:
      double_z: true 
      z_channels: 3 
      resolution: 256 
      in_channels: 3 
      out_ch: 3 
      ch: 128 
      ch_mult: 
      - 1 
      - 2 
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0

