model:
  target: AutoEncoder.autoencoder.AutoEncoderKL
  embed_dim: 3
  monitor: val/rec_loss
  params:
    ddconfig:
      double_z: True
      z_channels: 64
      resolution: 256
      in_channels: 3 
      out_ch: 3 
      ch: 128 
      ch_mult: 
      - 1 
      - 1
      - 2
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: [16, 8]
      dropout: 0.0
    lossconfig:
      target: VAE.loss.LPIPSWithDiscriminator
      params:
        disc_start: 50001
        kl_weight: 1.0e-06
        disc_weight: 0.5

    
  

